---
version: 2

builds:
  - goos:
      - linux
    goarch:
      - amd64
      # supporting arm is possible if we get CGO support
      # working in the github action/goreleaser pipeline.
      # - arm64
archives:
  - files:
      - example/*
      - public/css/*
      - public/js/*
      - public/index.tmpl
